# Generated by Django 4.0.4 on 2022-05-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockPaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usergame',
            name='select_el',
            field=models.IntegerField(null=True),
        ),
    ]
